---
- name: Include OS specific tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Install packages
  ansible.builtin.package:
    name:
      - "winehq-{{ wine_branch }}"
    state: latest
  tags:
    - skip_ansible_lint # Package installs should not use latest.
